version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
    container_name: insurance-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - insurance-network

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "8501:8501"
    container_name: insurance-ui
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - insurance-network

networks:
  insurance-network:
    driver: bridge
